import type { Metadata } from "next";
import { absoluteUrl, siteConfig } from "./site";

type BuildMetadataInput = {
  title: string;
  description: string;
  /** Route path, e.g. "/blog". Used for the canonical URL and og:url. */
  path: string;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  tags?: string[];
  /** Set to true for pages that should not be indexed. */
  noIndex?: boolean;
  /** Skip the "%s | MarketScope" title template (used by the home page). */
  absoluteTitle?: boolean;
  /** Route path of a page-specific social card. Defaults to the site-wide card. */
  image?: string;
};

/**
 * Builds consistent per-page metadata: title, description, canonical,
 * Open Graph and Twitter cards. The default card is generated by
 * `opengraph-image.tsx`; articles pass their own via `image`.
 */
export function buildMetadata({
  title,
  description,
  path,
  type = "website",
  publishedTime,
  modifiedTime,
  authors,
  tags,
  noIndex = false,
  absoluteTitle = false,
  image = "/opengraph-image",
}: BuildMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const images = [{ url: image, width: 1200, height: 630, alt: siteConfig.name }];

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type,
      images,
      ...(type === "article" ? { publishedTime, modifiedTime, authors, tags } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      site: siteConfig.twitter,
      images: images.map((i) => i.url),
    },
    robots: noIndex ? { index: false, follow: true } : { index: true, follow: true },
  };
}
